import { PrismaClient, Role } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.experience.deleteMany();
  await prisma.account.deleteMany();
  await prisma.session.deleteMany();
  await prisma.verificationToken.deleteMany();
  await prisma.user.deleteMany();

  const host = await prisma.user.upsert({
    where: { email: "host@example.com" },
    update: { role: Role.HOST },
    create: {
      name: "Host Demo",
      email: "host@example.com",
      role: Role.HOST,
    },
  });

  await prisma.user.upsert({
    where: { email: "client@example.com" },
    update: { role: Role.CLIENT },
    create: {
      name: "Client Demo",
      email: "client@example.com",
      role: Role.CLIENT,
    },
  });

  // 20 diverse experiences covering different filter scenarios
  await prisma.experience.createMany({
    data: [
      {
        title: "Wine tasting in Tuscany",
        location: "Italy",
        price: 120,
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=600&fit=crop",
        description: "Explore Tuscany's vineyards with a local expert. Duration: 3 hours. Available in afternoon and evening.",
        userId: host.id,
        activityTypes: ["ART_AND_CULTURE", "FOOD_AND_DRINK"],
        timeOfDays: ["AFTERNOON", "EVENING"],
        duration: "ONE_TO_4H",
        specials: ["LIKELY_TO_SELL_OUT", "NEW_EXPERIENCE"],
      },
      {
        title: "Surf camp in Bali",
        location: "Indonesia",
        price: 200,
        rating: 4.8,
        image: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&h=600&fit=crop",
        description: "Learn to surf on Bali's famous waves with local guides. Full day experience.",
        userId: host.id,
        activityTypes: ["SPORTS", "NATURE_AND_OUTDOORS"],
        timeOfDays: ["MORNING", "AFTERNOON"],
        duration: "FOUR_H_TO_1_DAY",
        specials: ["LIKELY_TO_SELL_OUT", "NEW_EXPERIENCE"],
      },
      {
        title: "Morning Yoga on the Beach",
        location: "Maldives",
        price: 45,
        rating: 4.7,
        image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&h=600&fit=crop",
        description: "Start your day with sunrise yoga session. Duration: 1 hour.",
        userId: host.id,
        activityTypes: ["WELLNESS", "NATURE_AND_OUTDOORS"],
        timeOfDays: ["MORNING"],
        duration: "UP_TO_1H",
        specials: ["FREE_CANCELLATION"],
      },
      {
        title: "Street Food Tour in Bangkok",
        location: "Thailand",
        price: 35,
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop",
        description: "Discover authentic Thai street food. Evening tour, 2-3 hours.",
        userId: host.id,
        activityTypes: ["FOOD_AND_DRINK", "TOURS"],
        timeOfDays: ["EVENING"],
        duration: "ONE_TO_4H",
        specials: ["DEALS_AND_DISCOUNTS", "SKIP_THE_LINE"],
      },
      {
        title: "Louvre Museum Private Tour",
        location: "Paris, France",
        price: 150,
        rating: 4.8,
        image: "https://images.unsplash.com/photo-1628811599940-5307c9cd5ba4?q=80&w=1786&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "Skip the lines with private guided tour. Morning or afternoon, 4 hours.",
        userId: host.id,
        activityTypes: ["ART_AND_CULTURE", "SIGHTSEEING"],
        timeOfDays: ["MORNING", "AFTERNOON"],
        duration: "ONE_TO_4H",
        specials: ["SKIP_THE_LINE", "PRIVATE_TOUR"],
      },
      {
        title: "Mountain Hiking Adventure",
        location: "Switzerland",
        price: 180,
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=600&fit=crop",
        description: "Full day hiking experience in the Swiss Alps. Full day adventure.",
        userId: host.id,
        activityTypes: ["SPORTS", "NATURE_AND_OUTDOORS"],
        timeOfDays: ["MORNING", "AFTERNOON"],
        duration: "FOUR_H_TO_1_DAY",
        specials: ["FREE_CANCELLATION", "LIKELY_TO_SELL_OUT"],
      },
      {
        title: "Jazz Night in New Orleans",
        location: "USA",
        price: 65,
        rating: 4.6,
        image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop",
        description: "Evening jazz experience in the French Quarter. 2 hours.",
        userId: host.id,
        activityTypes: ["ENTERTAINMENT"],
        timeOfDays: ["EVENING"],
        duration: "ONE_TO_4H",
        specials: ["DEALS_AND_DISCOUNTS"],
      },
      {
        title: "Cooking Class: Italian Pasta Making",
        location: "Rome, Italy",
        price: 85,
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=600&fit=crop",
        description: "Learn to make authentic Italian pasta. Afternoon class, 3 hours.",
        userId: host.id,
        activityTypes: ["FOOD_AND_DRINK", "ART_AND_CULTURE"],
        timeOfDays: ["AFTERNOON"],
        duration: "ONE_TO_4H",
        specials: ["NEW_EXPERIENCE"],
      },
      {
        title: "Hot Air Balloon Sunrise",
        location: "Cappadocia, Turkey",
        price: 250,
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?w=800&h=600&fit=crop",
        description: "Early morning hot air balloon ride. 1 hour flight plus preparation.",
        userId: host.id,
        activityTypes: ["TOURS", "SIGHTSEEING"],
        timeOfDays: ["MORNING"],
        duration: "UP_TO_1H",
        specials: ["LIKELY_TO_SELL_OUT", "PRIVATE_TOUR"],
      },
      {
        title: "Wine & Cheese Evening",
        location: "Barcelona, Spain",
        price: 55,
        rating: 4.7,
        image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=600&fit=crop",
        description: "Evening wine and cheese pairing experience. 2 hours.",
        userId: host.id,
        activityTypes: ["FOOD_AND_DRINK", "ART_AND_CULTURE"],
        timeOfDays: ["EVENING"],
        duration: "ONE_TO_4H",
        specials: ["FREE_CANCELLATION"],
      },
      {
        title: "Cycling Tour of Amsterdam",
        location: "Netherlands",
        price: 40,
        rating: 4.8,
        image: "https://images.unsplash.com/photo-1544984243-ec57ea16fe25?w=800&h=600&fit=crop",
        description: "Explore Amsterdam by bike. Morning or afternoon, 2-3 hours.",
        userId: host.id,
        activityTypes: ["TOURS", "SIGHTSEEING", "SPORTS"],
        timeOfDays: ["MORNING", "AFTERNOON"],
        duration: "ONE_TO_4H",
        specials: ["DEALS_AND_DISCOUNTS"],
      },
      {
        title: "Spa & Wellness Retreat",
        location: "Iceland",
        price: 300,
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&h=600&fit=crop",
        description: "Full day wellness retreat with spa treatments. Full day experience.",
        userId: host.id,
        activityTypes: ["WELLNESS"],
        timeOfDays: ["MORNING", "AFTERNOON"],
        duration: "FOUR_H_TO_1_DAY",
        specials: ["FREE_CANCELLATION", "PRIVATE_TOUR"],
      },
      {
        title: "Street Art Walking Tour",
        location: "Berlin, Germany",
        price: 25,
        rating: 4.6,
        image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=600&fit=crop",
        description: "Discover Berlin's street art scene. Afternoon tour, 2 hours.",
        userId: host.id,
        activityTypes: ["ART_AND_CULTURE", "TOURS", "SIGHTSEEING"],
        timeOfDays: ["AFTERNOON"],
        duration: "ONE_TO_4H",
        specials: ["DEALS_AND_DISCOUNTS", "SKIP_THE_LINE"],
      },
      {
        title: "Wildlife Safari Experience",
        location: "Kenya",
        price: 450,
        rating: 5.0,
        image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&h=600&fit=crop",
        description: "3-day safari adventure with professional guides. Multi-day experience.",
        userId: host.id,
        activityTypes: ["NATURE_AND_OUTDOORS", "TOURS"],
        timeOfDays: ["MORNING", "AFTERNOON"],
        duration: "ONE_TO_3_DAYS",
        specials: ["LIKELY_TO_SELL_OUT", "PRIVATE_TOUR", "NEW_EXPERIENCE"],
      },
      {
        title: "Rock Climbing Adventure",
        location: "Yosemite, USA",
        price: 175,
        rating: 4.8,
        image: "https://images.unsplash.com/photo-1601224748193-d24f166b5c77?q=80&w=928&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D?w=800&h=600&fit=crop",
        description: "Full day rock climbing with certified instructors.",
        userId: host.id,
        activityTypes: ["SPORTS", "NATURE_AND_OUTDOORS"],
        timeOfDays: ["MORNING", "AFTERNOON"],
        duration: "FOUR_H_TO_1_DAY",
        specials: ["FREE_CANCELLATION"],
      },
      {
        title: "Traditional Tea Ceremony",
        location: "Kyoto, Japan",
        price: 60,
        rating: 4.7,
        image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&h=600&fit=crop",
        description: "Authentic Japanese tea ceremony experience. Morning or afternoon, 1 hour.",
        userId: host.id,
        activityTypes: ["ART_AND_CULTURE", "FOOD_AND_DRINK"],
        timeOfDays: ["MORNING", "AFTERNOON"],
        duration: "UP_TO_1H",
        specials: ["NEW_EXPERIENCE"],
      },
      {
        title: "Night Market Food Tour",
        location: "Taipei, Taiwan",
        price: 42,
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop",
        description: "Evening food tour through night markets. 3 hours.",
        userId: host.id,
        activityTypes: ["FOOD_AND_DRINK", "ENTERTAINMENT"],
        timeOfDays: ["EVENING"],
        duration: "ONE_TO_4H",
        specials: ["DEALS_AND_DISCOUNTS", "SKIP_THE_LINE"],
      },
      {
        title: "Meditation & Mindfulness Retreat",
        location: "Bali, Indonesia",
        price: 120,
        rating: 4.8,
        image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=600&fit=crop",
        description: "Morning meditation session in serene setting. 2 hours.",
        userId: host.id,
        activityTypes: ["WELLNESS"],
        timeOfDays: ["MORNING"],
        duration: "ONE_TO_4H",
        specials: ["FREE_CANCELLATION", "NEW_EXPERIENCE"],
      },
      {
        title: "Photography Tour: Golden Hour",
        location: "Santorini, Greece",
        price: 95,
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&h=600&fit=crop",
        description: "Sunset photography tour with professional photographer. Evening, 2 hours.",
        userId: host.id,
        activityTypes: ["TOURS", "SIGHTSEEING", "ART_AND_CULTURE"],
        timeOfDays: ["EVENING"],
        duration: "ONE_TO_4H",
        specials: ["PRIVATE_TOUR", "LIKELY_TO_SELL_OUT"],
      },
      {
        title: "Kayaking in Fjords",
        location: "Norway",
        price: 165,
        rating: 4.7,
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
        description: "Full day kayaking adventure through Norwegian fjords.",
        userId: host.id,
        activityTypes: ["SPORTS", "NATURE_AND_OUTDOORS", "TOURS"],
        timeOfDays: ["MORNING", "AFTERNOON"],
        duration: "FOUR_H_TO_1_DAY",
        specials: ["FREE_CANCELLATION"],
      },
    ],
  });

  console.log("✅ Database seeded with 20 diverse experiences!");
}

main()
  .catch((e) => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
